<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Rectangle" Id="{c6305f9d-6f14-427d-a3fe-5979eff01bb1}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_Rectangle IMPLEMENTS I_Shape
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Draw" Id="{4c933931-c4e1-4633-a3b1-1c305296702a}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD M_Draw : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_HINT, 'Draw rectangle', '');
M_Draw := TRUE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>