<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Shape" Id="{c353f373-9ede-4c31-83a9-a7197bda022a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT FB_Shape
VAR
	_color : ITF_color;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Draw" Id="{238a75eb-020f-4c4c-9456-88d1cd5ae639}">
      <Declaration><![CDATA[METHOD ABSTRACT Draw : STRING

]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{42591783-ae3d-48ef-8d1f-58b95c90d4c2}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	Color : ITF_Color;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^._color := Color;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>