<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_CustomShape" Id="{043835f9-50bb-4934-a8b5-7b0e8a602ef0}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'} 
FUNCTION_BLOCK FB_CustomShape IMPLEMENTS I_Shape
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Draw" Id="{58c546e4-cf3f-45eb-84af-b5c009232210}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD M_Draw : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_HINT, 'Draw custom shape', '');
M_Draw := TRUE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>