<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_Motor" Id="{6caff27d-6c1b-44a6-a830-e43bb9eb0ae4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Motor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	TempSensor					: I_TempSensor;
	nTemperature 				: REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nTemperature := TempSensor.P_DegreesC;]]></ST>
    </Implementation>
    <Method Name="FB_Init" Id="{2aa0dc3d-6dbf-49a8-be50-28e892b9218f}">
      <Declaration><![CDATA[METHOD FB_Init : BOOL
VAR_INPUT
    bInitRetains 		: BOOL ; // if TRUE, the retain variables are initialized (reset warm / reset cold)
    bInCopyCode  		: BOOL ; // if TRUE, the instance afterwards gets moved into the copy code (online change)
	TempSensor			: I_TempSensor;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[this^.TempSensor := TempSensor;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Motor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Motor.FB_Init">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>