<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_ActorRotateCCWCommand" Id="{741dd56c-c740-439b-a04b-43b7462a92eb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ActorRotateCCWCommand IMPLEMENTS I_Command
VAR
	refFlyingHoist : REFERENCE TO FB_FlyingHoist;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{4984f520-6602-49c5-bfe2-d6a0337076d4}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refFlyingHoist)) THEN
	THIS^.refFlyingHoist.HoistEnable();
	THIS^.refFlyingHoist.ActorRotateCCW();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{c6449c30-ae6f-419c-8bf6-b698a64e097f}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains 	: BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode 	: BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refFlyingHoist 	: REFERENCE TO FB_FlyingHoist;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refFlyingHoist)) THEN
	THIS^.refFlyingHoist REF= refFlyingHoist;
ELSE
	THIS^.refFlyingHoist REF= 0;
END_IF
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ActorRotateCCWCommand">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ActorRotateCCWCommand.Execute">
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ActorRotateCCWCommand.FB_init">
      <LineId Id="8" Count="4" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>