<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_ActorUpCommand" Id="{7b9aec9c-bd26-4003-9ca5-999ebeba90c2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ActorUpCommand IMPLEMENTS I_Command
VAR
	refFlyingHoist : REFERENCE TO FB_FlyingHoist;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{2f327d9f-d2e2-425f-853a-d933fdeff812}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refFlyingHoist)) THEN
	THIS^.refFlyingHoist.HoistEnable();
	THIS^.refFlyingHoist.ActorUp();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{ff58d0e0-9890-4845-89f4-318bf95c9a18}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains 	: BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode 	: BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refFlyingHoist 	: REFERENCE TO FB_FlyingHoist;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refFlyingHoist)) THEN
	THIS^.refFlyingHoist REF= refFlyingHoist;
ELSE
	THIS^.refFlyingHoist REF= 0;
END_IF]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ActorUpCommand">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ActorUpCommand.Execute">
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ActorUpCommand.FB_init">
      <LineId Id="8" Count="3" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>