<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_ActorDownCommand" Id="{2078b464-5b40-44e8-8a80-8b442178bb99}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ActorDownCommand IMPLEMENTS I_Command
VAR
	refFlyingHoist : REFERENCE TO FB_FlyingHoist;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{c276a850-a646-4234-97a7-07704f73885f}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refFlyingHoist)) THEN
	THIS^.refFlyingHoist.HoistEnable();
	THIS^.refFlyingHoist.ActorDown();
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{920cab80-d358-41f7-9d8d-cb464ed6e5e5}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains 	: BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode 	: BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refFlyingHoist 	: REFERENCE TO FB_FlyingHoist;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refFlyingHoist)) THEN
	THIS^.refFlyingHoist REF= refFlyingHoist;
ELSE
	THIS^.refFlyingHoist REF= 0;
END_IF
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ActorDownCommand">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ActorDownCommand.Execute">
      <LineId Id="5" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ActorDownCommand.FB_init">
      <LineId Id="9" Count="4" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>