<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_FirePyroModeCommand" Id="{b25aa89e-c419-4dc6-816c-0a0cfa2a379f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_FirePyroModeCommand IMPLEMENTS I_Command
VAR
	refFlameCannon : REFERENCE TO FB_FlameCannon;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{7eca64eb-b034-4d04-a9ed-f8ce686e7d45}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refFlameCannon)) THEN
	THIS^.refFlameCannon.On();
	THIS^.refFlameCannon.SetLevel(95.00);
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{6af10b78-705f-4e22-a7a6-661f4685e583}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains 	: BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode 	: BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refFlameCannon 	: REFERENCE TO FB_FlameCannon;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refFlameCannon)) THEN
	THIS^.refFlameCannon REF= refFlameCannon;
ELSE
	THIS^.refFlameCannon REF= 0;
END_IF]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_FirePyroModeCommand">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_FirePyroModeCommand.Execute">
      <LineId Id="5" Count="2" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_FirePyroModeCommand.FB_init">
      <LineId Id="8" Count="3" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>