<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_ActorStopRotateCommand" Id="{d2d2c4a2-f534-4e61-b3d8-6964c09c6f2a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ActorStopRotateCommand IMPLEMENTS I_Command
VAR
	refFlyingHoist : REFERENCE TO FB_FlyingHoist;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{36115dc0-74e8-4d32-868a-6526c95a3359}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refFlyingHoist)) THEN
	THIS^.refFlyingHoist.StopRotateCommand();
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{7ba8bf25-e2d2-463a-a7ad-b1cb80d36bdc}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains 	: BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode 	: BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refFlyingHoist 	: REFERENCE TO FB_FlyingHoist;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refFlyingHoist)) THEN
	THIS^.refFlyingHoist REF= refFlyingHoist;
ELSE
	THIS^.refFlyingHoist REF= 0;
END_IF
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ActorStopRotateCommand">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ActorStopRotateCommand.Execute">
      <LineId Id="5" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ActorStopRotateCommand.FB_init">
      <LineId Id="9" Count="4" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>