<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_ActorRotateCWCommand" Id="{7216a253-35d9-4921-9f53-031c51a2ce35}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ActorRotateCWCommand IMPLEMENTS I_Command
VAR
	refFlyingHoist : REFERENCE TO FB_FlyingHoist;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{598d4f78-ac77-42f9-a4d9-0ec86ac40c75}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refFlyingHoist)) THEN
	THIS^.refFlyingHoist.HoistEnable();
	THIS^.refFlyingHoist.ActorRotateCW();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{6e1ce23c-0b46-4816-8fd8-e53fecfa52ff}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains 	: BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode 	: BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refFlyingHoist 	: REFERENCE TO FB_FlyingHoist;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refFlyingHoist)) THEN
	THIS^.refFlyingHoist REF= refFlyingHoist;
ELSE
	THIS^.refFlyingHoist REF= 0;
END_IF]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ActorRotateCWCommand">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ActorRotateCWCommand.Execute">
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ActorRotateCWCommand.FB_init">
      <LineId Id="9" Count="3" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>