<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_MovingHeadOffCommand" Id="{7ac6b268-1904-407f-a3b1-73e26c02133d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MovingHeadOffCommand IMPLEMENTS I_Command
VAR
	refMovingHead : REFERENCE TO FB_MovingHead;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{ce92b5c6-96f3-4e1d-af6e-e2ef961a1197}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(THIS^.refMovingHead)) THEN
	THIS^.refMovingHead.Off();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{749ea78c-4f44-4848-bdd0-2719517e87ce}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains 	: BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode 	: BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refMovingHead 	: REFERENCE TO FB_MovingHead;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (__ISVALIDREF(refMovingHead)) THEN
	THIS^.refMovingHead REF= refMovingHead;
ELSE
	THIS^.refMovingHead REF= 0;
END_IF]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_MovingHeadOffCommand">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_MovingHeadOffCommand.Execute">
      <LineId Id="5" Count="1" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_MovingHeadOffCommand.FB_init">
      <LineId Id="9" Count="3" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>