<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{c7c31f80-c7d0-4df9-9a94-06a2d4614184}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbPepPizza 	: FB_PepperoniPizza;
	fbVegPizza 	: FB_VeggiePizza;
	
	bPepButton: BOOL;
	bVegButton: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbPepPizza.makePizza(bPepButton);
fbVegPizza.makePizza(bVegButton);
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="11" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>