<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="FB_StaticHandler_n" Id="{f6345661-8199-4758-9fde-99ce64e8894d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_StaticHandler_n EXTENDS FB_BaseHandler
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="handle" Id="{c21a65c0-c79d-491f-846b-1e1ecfabd480}">
      <Declaration><![CDATA[METHOD handle : BOOL
VAR_INPUT
	request	:	STRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_MSGBOX, request , '');
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_StaticHandler_n">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_StaticHandler_n.handle">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>