<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="FB_StaticHandler2" Id="{1673d7e5-bb05-4200-b815-2458555e1d50}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_StaticHandler2 EXTENDS FB_BaseHandler
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="handle" Id="{1a343a5d-7eaa-4598-a54c-9e5e6242e608}">
      <Declaration><![CDATA[METHOD handle : BOOL
VAR_INPUT
	request	:	STRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF request = 'Handler 2 Interupt' THEN
	ADSLOGSTR(ADSLOG_MSGTYPE_MSGBOX, request, ' ');
ELSE
	ADSLOGSTR(ADSLOG_MSGTYPE_MSGBOX, '@H2 Moving to next handler ', '');
	SUPER^.handle(request);
END_IF]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_StaticHandler2">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_StaticHandler2.handle">
      <LineId Id="3" Count="4" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>