<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="FB_Idle" Id="{08375453-5d76-0934-1a95-46e42d833973}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Idle IMPLEMENTS I_State
VAR_INPUT
	(* Pointer to the ATM Machine*)
	pATM_Machine	: POINTER TO FB_ATM_Machine;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cancel" Id="{65abf8fa-bea9-0656-26b8-1130a620e2a5}">
      <Declaration><![CDATA[METHOD Cancel : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Card_Ejected" Id="{529bb744-2dd3-091b-0da9-4215e7aa3d79}">
      <Declaration><![CDATA[METHOD Card_Ejected : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Card_Inserted" Id="{4a45be97-fabb-0bf6-3e82-4d00f394dbe8}">
      <Declaration><![CDATA[METHOD Card_Inserted : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'Card has been inserted!', '');
pATM_Machine^.SetState(pATM_Machine^.ServingCustomerState);]]></ST>
      </Implementation>
    </Method>
    <Property Name="Description" Id="{32d6cbbd-8d4f-077c-1475-851fe7226d1c}">
      <Declaration><![CDATA[PROPERTY Description : E_StateDescription
]]></Declaration>
      <Get Name="Get" Id="{6ab89e4c-9a5b-0791-3189-ae0d014fa703}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Description := E_StateDescription.Idle;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Failure" Id="{1a918f8a-e3c3-04cc-3136-10375b9740ac}">
      <Declaration><![CDATA[METHOD Failure : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_Init" Id="{c511d069-a148-0ad4-3acd-b9033977d1e7}">
      <Declaration><![CDATA[METHOD FB_Init : BOOL
VAR_INPUT
	(* if TRUE, the retain variables are initialized (warm start / cold start)*)
	bInitRetains	: BOOL;
	(* if TRUE, the instance afterwards gets moved into the copy code (online change)*)
	bInCopyCode	: BOOL;
	(* Pointer to the ATM Machine*)
	pATM_Machine	: POINTER TO FB_ATM_Machine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.pATM_Machine := pATM_Machine;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Op" Id="{d58a9927-21a9-057d-2612-bf7827879517}">
      <Declaration><![CDATA[METHOD Op : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Service" Id="{528a5b81-39cb-0ad8-390a-c4aba054ca09}">
      <Declaration><![CDATA[METHOD Service : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'Entering Service Mode...', '');
pATM_Machine^.SetState(pATM_Machine^.MaintenanceState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="SystemTest_OK" Id="{4d033fde-e0c2-0cdc-2375-e8648799e634}">
      <Declaration><![CDATA[METHOD SystemTest_OK : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Turn_Off" Id="{67b1520e-2467-05df-32c1-7bd367dd3066}">
      <Declaration><![CDATA[METHOD Turn_Off : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'Turning off machine...', '');
pATM_Machine^.SetState(pATM_Machine^.OffState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Turn_On" Id="{7891db3f-3e8c-02e0-0648-e26dcab5460c}">
      <Declaration><![CDATA[METHOD Turn_On : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Idle">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.Cancel">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.Card_Ejected">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.Card_Inserted">
      <LineId Id="7" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.Description.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.Failure">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.FB_Init">
      <LineId Id="12" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.Op">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.Service">
      <LineId Id="7" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.SystemTest_OK">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.Turn_Off">
      <LineId Id="7" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Idle.Turn_On">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>