<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="FB_Maintenance" Id="{422bee07-fab0-086f-2f20-2f473840af98}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Maintenance IMPLEMENTS I_State
VAR_INPUT
	(* Pointer to the ATM Machine*)
	pATM_Machine	: POINTER TO FB_ATM_Machine;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cancel" Id="{fc6c514b-2a24-0485-0094-7f9672024860}">
      <Declaration><![CDATA[METHOD Cancel : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Card_Ejected" Id="{f0c20272-59ca-04aa-17cf-f0dc9b6e6caa}">
      <Declaration><![CDATA[METHOD Card_Ejected : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Card_Inserted" Id="{8c8901b8-6177-09cf-0171-70900555bba1}">
      <Declaration><![CDATA[METHOD Card_Inserted : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Description" Id="{9563a445-e11a-0e6c-0c59-44fdd0b4d03f}">
      <Declaration><![CDATA[PROPERTY Description : E_StateDescription
]]></Declaration>
      <Get Name="Get" Id="{f4aa627d-a63a-0b8c-16ea-3a081815301d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Description := E_StateDescription.Maintenance;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Failure" Id="{5c7b77fb-733d-070b-292d-1bd3ac175be9}">
      <Declaration><![CDATA[METHOD Failure : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_Init" Id="{724c03c1-3a42-00fb-371d-203832591578}">
      <Declaration><![CDATA[METHOD FB_Init : BOOL
VAR_INPUT
	(* if TRUE, the retain variables are initialized (warm start / cold start)*)
	bInitRetains	: BOOL;
	(* if TRUE, the instance afterwards gets moved into the copy code (online change)*)
	bInCopyCode	: BOOL;
	(* Pointer to the ATM Machine*)
	pATM_Machine	: POINTER TO FB_ATM_Machine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.pATM_Machine := pATM_Machine;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Op" Id="{d5b1852a-c23d-0073-23f0-eda99df56713}">
      <Declaration><![CDATA[METHOD Op : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'Exiting Service mode, going to self test', '');
pATM_Machine^.SetState(pATM_Machine^.SelfTestState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Service" Id="{5643db20-9040-00ed-10c1-8d0666a21e31}">
      <Declaration><![CDATA[METHOD Service : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SystemTest_OK" Id="{e4e24f0f-5074-0c16-0c9d-ff973e36ac56}">
      <Declaration><![CDATA[METHOD SystemTest_OK : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Turn_Off" Id="{904c14f7-b1ec-0e92-0ab3-92a000c17c86}">
      <Declaration><![CDATA[METHOD Turn_Off : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Turn_On" Id="{77c37fbd-c644-01ab-24b8-e342a38b3aae}">
      <Declaration><![CDATA[METHOD Turn_On : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Maintenance">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.Cancel">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.Card_Ejected">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.Card_Inserted">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.Description.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.Failure">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.FB_Init">
      <LineId Id="12" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.Op">
      <LineId Id="7" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.Service">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.SystemTest_OK">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.Turn_Off">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Maintenance.Turn_On">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>