<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="FB_ServingCustomer" Id="{2169bdb5-0da4-0ea5-24fe-5fde7652ce39}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ServingCustomer IMPLEMENTS I_State
VAR_INPUT
	(* Pointer to the ATM Machine*)
	pATM_Machine	: POINTER TO FB_ATM_Machine;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cancel" Id="{0e0fe738-b3e9-0358-2d81-02f6cd38afb2}">
      <Declaration><![CDATA[METHOD Cancel : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'Transaction canceled, going to idle...', '');
pATM_Machine^.SetState(pATM_Machine^.IdleState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Card_Ejected" Id="{747865e4-dec6-08e9-384e-b8fa1a87fd13}">
      <Declaration><![CDATA[METHOD Card_Ejected : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'Card has been ejected, going to idle...', '');
pATM_Machine^.SetState(pATM_Machine^.IdleState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Card_Inserted" Id="{496c6b96-2532-0095-24e3-1ab072d73dc9}">
      <Declaration><![CDATA[METHOD Card_Inserted : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Description" Id="{8489062d-1154-04dd-1950-3fc62e92bac3}">
      <Declaration><![CDATA[PROPERTY Description : E_StateDescription
]]></Declaration>
      <Get Name="Get" Id="{a852d8cb-c913-00cf-3bf9-dc37610b440f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Description := E_StateDescription.ServingCustomer;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Failure" Id="{aeaf7ee5-2b0b-09ab-1796-fa68bbf06b98}">
      <Declaration><![CDATA[METHOD Failure : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'Transaction failed, contact service...', '');
pATM_Machine^.SetState(pATM_Machine^.OutOfServiceState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_Init" Id="{f7335f31-dc20-01dd-07c2-500833277a92}">
      <Declaration><![CDATA[METHOD FB_Init : BOOL
VAR_INPUT
	(* if TRUE, the retain variables are initialized (warm start / cold start)*)
	bInitRetains	: BOOL;
	(* if TRUE, the instance afterwards gets moved into the copy code (online change)*)
	bInCopyCode	: BOOL;
	(* Pointer to the ATM Machine*)
	pATM_Machine	: POINTER TO FB_ATM_Machine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.pATM_Machine := pATM_Machine;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Op" Id="{9249b1da-093c-0417-3d7d-fb694f350cc8}">
      <Declaration><![CDATA[METHOD Op : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Service" Id="{6fbae138-be53-0222-29db-22d42af02186}">
      <Declaration><![CDATA[METHOD Service : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SystemTest_OK" Id="{058fed9a-4cbb-0ced-299f-a0df271f8cd4}">
      <Declaration><![CDATA[METHOD SystemTest_OK : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Turn_Off" Id="{f7a7925a-d73d-0675-1999-5077c1979473}">
      <Declaration><![CDATA[METHOD Turn_Off : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Turn_On" Id="{fdac9bf2-2e0e-06f4-364f-b3e5cdb12bf2}">
      <Declaration><![CDATA[METHOD Turn_On : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ServingCustomer">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.Cancel">
      <LineId Id="7" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.Card_Ejected">
      <LineId Id="7" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.Card_Inserted">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.Description.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.Failure">
      <LineId Id="7" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.FB_Init">
      <LineId Id="12" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.Op">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.Service">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.SystemTest_OK">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.Turn_Off">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_ServingCustomer.Turn_On">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>