<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="FB_StaticHandler3" Id="{e58e011c-6753-45fa-8a7c-dd844d785e61}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_StaticHandler3 EXTENDS FB_BaseHandler
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="handle" Id="{04dc4e27-3d51-411c-b241-24e2b1d80e78}">
      <Declaration><![CDATA[METHOD handle : BOOL
VAR_INPUT
	request	:	STRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF request = 'Handler 3 Interupt' THEN
	ADSLOGSTR(ADSLOG_MSGTYPE_MSGBOX, request, ' ');
ELSE
	ADSLOGSTR(ADSLOG_MSGTYPE_MSGBOX, '@H3 Moving to next handler ', '');
	SUPER^.handle(request);
END_IF]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_StaticHandler3">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_StaticHandler3.handle">
      <LineId Id="3" Count="4" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>