<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_Subscriber" Id="{40122c7b-204f-4d8a-8934-d01a04594cc3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_Subscriber IMPLEMENTS I_Subscriber
VAR
	_Value				: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="ActualValue" Id="{bfb72149-d202-4acb-8317-036f3b16962d}">
      <Declaration><![CDATA[PROPERTY ActualValue : LREAL]]></Declaration>
      <Get Name="Get" Id="{a97714f2-db45-4076-9b3d-9c5a1c6910e5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[ActualValue := THIS^._Value;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Update" Id="{ab10fc4b-83d9-407a-af6c-0bdbb13792fb}">
      <Declaration><![CDATA[METHOD PUBLIC Update : BOOL
VAR_INPUT
	Value	: LREAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^._Value := Value;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Subscriber">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Subscriber.ActualValue.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Subscriber.Update">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>