<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="FB_Off" Id="{77e4ed3a-e16e-0567-22df-368777bf9b32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Off IMPLEMENTS I_State
VAR_INPUT
	(* Pointer to the ATM Machine*)
	pATM_Machine	: POINTER TO FB_ATM_Machine;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cancel" Id="{e3a6cfd6-6764-0ca5-3403-c5b3f56cd495}">
      <Declaration><![CDATA[METHOD Cancel : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Card_Ejected" Id="{1c835f53-df5b-0715-2dc8-72b18fbcec93}">
      <Declaration><![CDATA[METHOD Card_Ejected : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Card_Inserted" Id="{2426d402-ea1d-097c-3df2-009aefb9d42b}">
      <Declaration><![CDATA[METHOD Card_Inserted : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Description" Id="{1255de27-539f-0603-0eb2-fe6707b9ed99}">
      <Declaration><![CDATA[PROPERTY Description : E_StateDescription
]]></Declaration>
      <Get Name="Get" Id="{c0d1b000-d69e-0f80-25cf-a58160038f5f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Description := E_StateDescription.Off;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Failure" Id="{73f3ab78-6cbd-01ce-0db9-9456e1f7b559}">
      <Declaration><![CDATA[METHOD Failure : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_Init" Id="{8ffe180d-8c71-0b11-1655-ea2db27e5031}">
      <Declaration><![CDATA[METHOD FB_Init : BOOL
VAR_INPUT
	(* if TRUE, the retain variables are initialized (warm start / cold start)*)
	bInitRetains	: BOOL;
	(* if TRUE, the instance afterwards gets moved into the copy code (online change)*)
	bInCopyCode	: BOOL;
	(* Pointer to the ATM Machine*)
	pATM_Machine	: POINTER TO FB_ATM_Machine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.pATM_Machine := pATM_Machine;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Op" Id="{47dc5cca-e0fc-01e7-28c5-c1653130abde}">
      <Declaration><![CDATA[METHOD Op : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Service" Id="{6ffc26dc-e3cc-06c8-0c08-82df71cb91b5}">
      <Declaration><![CDATA[METHOD Service : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SystemTest_OK" Id="{46dc5e76-4dd6-0eac-1ba8-ab13362276aa}">
      <Declaration><![CDATA[METHOD SystemTest_OK : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Turn_Off" Id="{c404dd17-467e-07fc-3ffd-8d27099a5005}">
      <Declaration><![CDATA[METHOD Turn_Off : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'Machine is already off!', '');]]></ST>
      </Implementation>
    </Method>
    <Method Name="Turn_On" Id="{5f5279f7-f1fa-0345-248c-d404f98f194c}">
      <Declaration><![CDATA[METHOD Turn_On : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'Turning on machine...', '');
pATM_Machine^.SetState(pATM_Machine^.SelfTestState);]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Off">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.Cancel">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.Card_Ejected">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.Card_Inserted">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.Description.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.Failure">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.FB_Init">
      <LineId Id="12" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.Op">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.Service">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.SystemTest_OK">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.Turn_Off">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Off.Turn_On">
      <LineId Id="4" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>