<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="FB_SelfTest" Id="{bf530f68-0b58-001a-33dc-b8df2ba985a6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SelfTest IMPLEMENTS I_State
VAR_INPUT
	(* Pointer to the ATM Machine*)
	pATM_Machine	: POINTER TO FB_ATM_Machine;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cancel" Id="{ec583400-85a2-0439-03ef-a260f6c24af6}">
      <Declaration><![CDATA[METHOD Cancel : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Card_Ejected" Id="{241d4a32-2c17-08a8-2247-391cc109267f}">
      <Declaration><![CDATA[METHOD Card_Ejected : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Card_Inserted" Id="{5dfbfab2-9050-0470-38d9-060a24f08e38}">
      <Declaration><![CDATA[METHOD Card_Inserted : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Description" Id="{49a17546-5a47-0724-13e3-9f9fa5de2c14}">
      <Declaration><![CDATA[PROPERTY Description : E_StateDescription
]]></Declaration>
      <Get Name="Get" Id="{25a9bd05-a407-0600-04e8-195918bff5e7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Description := E_StateDescription.SelfTest;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Failure" Id="{02401ffa-9399-0930-3b2c-286699b159c8}">
      <Declaration><![CDATA[METHOD Failure : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'System Test Fail, going to Out of Service', '');
pATM_Machine^.SetState(pATM_Machine^.OutOfServiceState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_Init" Id="{2ba494aa-bbc3-0f48-1716-5635010fb2f5}">
      <Declaration><![CDATA[METHOD FB_Init : BOOL
VAR_INPUT
	(* if TRUE, the retain variables are initialized (warm start / cold start)*)
	bInitRetains	: BOOL;
	(* if TRUE, the instance afterwards gets moved into the copy code (online change)*)
	bInCopyCode	: BOOL;
	(* Pointer to the ATM Machine*)
	pATM_Machine	: POINTER TO FB_ATM_Machine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.pATM_Machine := pATM_Machine;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Op" Id="{5a1a51f6-c898-05f2-1efd-750d1b4fe95c}">
      <Declaration><![CDATA[METHOD Op : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Service" Id="{b2723076-8d13-0f83-0514-3e1e79bed386}">
      <Declaration><![CDATA[METHOD Service : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SystemTest_OK" Id="{08998860-6ca0-06a3-2122-3d229dad0ca4}">
      <Declaration><![CDATA[METHOD SystemTest_OK : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_LOG, 'System Test Pass, going to Idel', '');
pATM_Machine^.SetState(pATM_Machine^.IdleState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Turn_Off" Id="{7e765441-1066-0b91-24ae-fa0271431b4f}">
      <Declaration><![CDATA[METHOD Turn_Off : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Turn_On" Id="{9a05e5cf-00c6-0992-1763-02b679060675}">
      <Declaration><![CDATA[METHOD Turn_On : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SelfTest">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.Cancel">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.Card_Ejected">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.Card_Inserted">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.Description.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.Failure">
      <LineId Id="7" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.FB_Init">
      <LineId Id="12" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.Op">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.Service">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.SystemTest_OK">
      <LineId Id="7" Count="0" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.Turn_Off">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_SelfTest.Turn_On">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>