<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Black" Id="{25133850-c5b4-4409-ae57-f1dbf04be7a4}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_Black IMPLEMENTS I_Color
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Fill" Id="{97774111-632e-441e-8ba9-2c360709bf52}">
      <Declaration><![CDATA[
METHOD M_Fill : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_HINT, 'Paint Black', '');
M_Fill := TRUE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>