<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Red" Id="{3af52522-8a45-41d6-940a-4988b9b31cf6}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_Red IMPLEMENTS I_Color
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Fill" Id="{69db6a5a-b341-4515-9fd5-68d949a4e314}">
      <Declaration><![CDATA[
METHOD M_Fill : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_HINT, 'Paint Red', '');
M_Fill := TRUE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>