<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Yellow" Id="{0f08c85f-8c65-4f2b-8312-1a34a6ee00f4}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_Yellow IMPLEMENTS I_Color
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Fill" Id="{6ad1cfcd-39e4-49fd-b1dc-eea5f3951bdf}">
      <Declaration><![CDATA[
METHOD M_Fill : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ADSLOGSTR(ADSLOG_MSGTYPE_HINT, 'Paint Yellow', '');
M_Fill := TRUE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>