<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{4397753d-6707-4ee1-9ec6-9f41f8444ae4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbSensor1		: FB_PT100;
	fbMotor1		: FB_Motor(TempSensor := fbSensor1);
	fbSensor2		: FB_PT1000;
	fbMotor2		: FB_Motor(fbSensor2);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Motors
fbSensor1();
fbMotor1();	
fbSensor2();
fbMotor2();	
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="10" Count="3" />
      <LineId Id="2" Count="0" />
      <LineId Id="21" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>