<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ElectricAdapterMotor" Id="{b69eb29b-3558-46ff-b1f1-f25e269725c2}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK ElectricAdapterMotor EXTENDS Motor
VAR
	pElectricEngine : POINTER TO ElectricMotor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_exit" Id="{845c3ac7-e64b-4656-bd7f-909a551f9694}">
      <Declaration><![CDATA[METHOD FB_exit : BOOL
VAR_INPUT
	bInCopyCode : BOOL; // if TRUE, the exit method is called for exiting an instance that is copied afterwards (online change).
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[__DELETE (pElectricEngine);]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{6c724098-dd2e-42cc-8617-7b0fce3758be}">
      <Declaration><![CDATA[
METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[pElectricEngine := __NEW(ElectricMotor);]]></ST>
      </Implementation>
    </Method>
    <Method Name="LoadFuel" Id="{730b5226-e1b4-4962-a3d3-9d07151c17f2}">
      <Declaration><![CDATA[METHOD PUBLIC LoadFuel

]]></Declaration>
      <Implementation>
        <ST><![CDATA[pElectricEngine^.Plug();]]></ST>
      </Implementation>
    </Method>
    <Method Name="SpeedUp" Id="{9641755b-0306-4223-a9ab-e3a4b3dbcda5}">
      <Declaration><![CDATA[METHOD PUBLIC SpeedUp

]]></Declaration>
      <Implementation>
        <ST><![CDATA[pElectricEngine^.Travel();]]></ST>
      </Implementation>
    </Method>
    <Method Name="StartUp" Id="{b54191ab-3f4d-472b-a836-aba66da3a43f}">
      <Declaration><![CDATA[METHOD PUBLIC StartUp

]]></Declaration>
      <Implementation>
        <ST><![CDATA[pElectricEngine^.Connect();
pElectricEngine^.Activate();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{09b6fda3-fff6-431f-8dcd-03f11369fa2d}">
      <Declaration><![CDATA[METHOD PUBLIC Stop

]]></Declaration>
      <Implementation>
        <ST><![CDATA[pElectricEngine^.Deactivate();
pElectricEngine^.Stop();]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>