<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Motor" Id="{3f55ef3a-1b19-4ac3-af6a-07651b20dd1a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT Motor

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="LoadFuel" Id="{b9f76f1f-c6b9-4a8f-b7ae-3a7493403678}">
      <Declaration><![CDATA[METHOD PUBLIC ABSTRACT LoadFuel

]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SpeedUp" Id="{76cae08d-6f11-497d-977a-75be8b98cbec}">
      <Declaration><![CDATA[METHOD PUBLIC ABSTRACT SpeedUp

]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="StartUp" Id="{51fbf7ae-0425-47d7-9b55-ca25c5d2db59}">
      <Declaration><![CDATA[METHOD PUBLIC ABSTRACT StartUp

]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{0af60e0e-884c-449d-b617-42909576f1dc}">
      <Declaration><![CDATA[METHOD PUBLIC ABSTRACT Stop

]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>