<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FB_Colleague" Id="{afb6d582-cdd4-4e93-9757-95f2ec75b624}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Colleague IMPLEMENTS I_Colleague
VAR_INPUT
	iMediator : REFERENCE TO I_Mediator; // Mediator Interface
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="operation" Id="{2a639bd1-c628-4980-8313-74cc776e7c0a}">
      <Declaration><![CDATA[METHOD operation : BOOL
VAR_INPUT
	event : STRING;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF __ISVALIDREF(iMediator) THEN
	iMediator.notify(THIS^,event);
END_IF
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Colleague">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Colleague.operation">
      <LineId Id="9" Count="2" />
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>